apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: kafkatopic02
  labels:
    strimzi.io/cluster: kafka-dc
spec:
  partitions: 9
  replicas: 3
  config:
    retention.ms: 604800000
    cleanup.policy: delete
    time.precision.mode: adaptive
#    compression.type: zstd
