 - job_name: x509-endpoint
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: monitoring;x509-certificate-exporter-headless;metrics
      - source_labels: [__meta_kubernetes_endpoint_node_name]
        target_label: instance
        regex: '([^:;]+)((:[0-9]+)?|;(.*))'
        replacement: '${1}'